### ISSUE TITLE
1.16 Console error

### ISSUE THREAD

**Issue by BeastPsycho** [pashavoid/ReputationPlus#2]
`7.11 20:36:13 [Server] ERROR Could not pass event InventoryClickEvent to ReputationPlus v0.4
27.11 20:36:13 [Server] INFO java.lang.NullPointerException: null
27.11 20:36:13 [Server] INFO at ru.pashavoid.reputationplus.gui.PlayerGUI.<init>(PlayerGUI.java:31) ~[?:?]
27.11 20:36:13 [Server] INFO at ru.pashavoid.reputationplus.Events.onInventoryClick(Events.java:70) ~[?:?]
27.11 20:36:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1017.execute(Unknown Source) ~[?:?]
27.11 20:36:13 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2527) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1265) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
27.11 20:36:14 [Server] ERROR Could not pass event InventoryClickEvent to ReputationPlus v0.4
27.11 20:36:14 [Server] INFO java.lang.NullPointerException: null
27.11 20:36:14 [Server] INFO at ru.pashavoid.reputationplus.gui.PlayerGUI.<init>(PlayerGUI.java:31) ~[?:?]
27.11 20:36:14 [Server] INFO at ru.pashavoid.reputationplus.Events.onInventoryClick(Events.java:70) ~[?:?]
27.11 20:36:14 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1017.execute(Unknown Source) ~[?:?]
27.11 20:36:14 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Multicraft] Skipped 18 lines due to rate limit (30/s)
27.11 20:36:14 [Server] ERROR Could not pass event InventoryClickEvent to ReputationPlus v0.4
27.11 20:36:14 [Server] INFO java.lang.NullPointerException: null
27.11 20:36:14 [Server] INFO at ru.pashavoid.reputationplus.gui.PlayerGUI.<init>(PlayerGUI.java:31) ~[?:?]
27.11 20:36:14 [Server] INFO at ru.pashavoid.reputationplus.Events.onInventoryClick(Events.java:70) ~[?:?]
27.11 20:36:14 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1017.execute(Unknown Source) ~[?:?]
27.11 20:36:14 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2527) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
27.11 20:36:15 [Server] ERROR Could not pass event InventoryClickEvent to ReputationPlus v0.4
27.11 20:36:15 [Server] INFO java.lang.NullPointerException: null
27.11 20:36:15 [Server] INFO at ru.pashavoid.reputationplus.gui.PlayerGUI.<init>(PlayerGUI.java:31) ~[?:?]
27.11 20:36:15 [Server] INFO at ru.pashavoid.reputationplus.Events.onInventoryClick(Events.java:70) ~[?:?]
27.11 20:36:15 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1017.execute(Unknown Source) ~[?:?]
27.11 20:36:15 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-296]
27.11 20:36:23 [Multicraft] Skipped 42 lines due to rate limit (30/s)`

1.16.2 - 1.16.4 paper/spigot minecraft server
The idea looks too great, can you fix this?
I tried activating sqlite in the config
Plugin opens the GUI, and doesnt do nothing

![Captura de pantalla (29)](https://user-images.githubusercontent.com/8921248/100491314-2a96bd80-30e8-11eb-9a0e-ddd41eeef7b4.png)

**Comment by pashavoid** [comment]
Check for the lang.cfg config and the "infoplayerrep" line"

**Comment by BeastPsycho** [comment]
#
#     Reputation+ 0.4
#     Author by pashavoid
#     File: lang.yml
#

en:
  lore: "Click on the player to interact with them"
  namemaingui: "Players"
  guiplayer: "Interact player"
  itsyou: "You can't vote for yourself."
  alreadyvote: "You have already voted for this player."
  vote: "You voted."
  infoplayerrep: "Player reputation"
  like: "Like"
  dislike: "Dislike"
  nextpage: "Next page"
  prevpage: "Prev page"
ru:
  lore: "Нажмите на игрока, чтобы взамодействовать с ним"
  namemaingui: "Игроки"
  guiplayer: "Взаимодействие с игроком"
  itsyou: "Вы не можете проголосовать за себя."
  alreadyvote: "Вы уже голосовали за этого игрока."
  infoplayerrep: "Репутация игрока"
  like: "Лайк"
  vote: "Вы проголосовали."
  dislike: "Дизлайк"
  nextpage: "След. страница"
  prevpage: "Пред. страница"

**Comment by pashavoid** [comment]
In the upcoming update, I will solve problems related to error crashes.
